const eventsArr = [
  {start: 0, duration: 15, title: `Exercise`},
  {start: 25, duration: 30, title: `Travel to work`},
  {start: 30, duration: 30, title: `Plan day`},
  {start: 60, duration: 15, title: `Review yesterday's commits`},
  {start: 100, duration: 15, title: `Code review`},
  {start: 180, duration: 90, title: `Have lunch with John`},
  {start: 360, duration: 30, title: `Skype call`},
  {start: 370, duration: 45, title: `Follow up with designer`},
  {start: 405, duration: 30, title: `Push up branch`},
  {start: 410, duration: 15, title: `Reading`},
  {start: 420, duration: 30, title: `Travel to partner's office`},
  {start: 445, duration: 30, title: `Meeting`},
  {start: 470, duration: 15, title: `Writing conclusions`},
  {start: 500, duration: 15, title: `Discussion`},
  {start: 510, duration: 20, title: `Push up dinner`},
  {start: 520, duration: 20, title: `Have a rest`},
  {start: 525, duration: 15, title: `Follow up with dev`},
  {start: 530, duration: 10, title: `Travel to work`},
]